name: Deploy to Google Cloud Run

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Authenticate to Google Cloud
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK (gcloud CLI)
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Log in to Google Cloud Artifact Registry
      run: |
        gcloud auth configure-docker "us-central1-docker.pkg.dev" --quiet


    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fastapi-repo/fastapi-app .

    - name: Push Docker image to GCR
      run: |
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fastapi-repo/fastapi-app:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy fastapi-app \
          --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fastapi-repo/fastapi-app:latest
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --service-account="${{ secrets.GCP_CLOUD_RUN_ACC }}" \ 
          --project="${{ secrets.GCP_PROJECT_ID }}"
